---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}

# unzip the input data file
unzip("activity.zip", overwrite = TRUE, exdir = ".")

# load the input data file
activityData <- read.csv("activity.csv")
##activityData$date <- strptime(as.character(activityData$date), "%Y-%m-%d")
```

## What is the mean total number of steps taken per day?

```{r}

# Calculate the total number of steps taken per day (ignoring NAs)
aggregatedData <- aggregate(steps~date, data=activityData, FUN="sum", na.action = na.omit)

# Histogram of the total number of steps taken per day
with(aggregatedData, hist(steps, main = "Number of steps per day", xlab = "Steps per day", col="red"))

# Report the mean and median of the total number of steps taken per day
mean(aggregatedData$steps)
median(aggregatedData$steps)
```

## What is the average daily activity pattern?

```{r}
# calculate the mean of steps taken per 5 min inerval acros all days
aggregatedData2 <- aggregate(steps~interval, data=activityData, FUN="mean", na.action = na.omit)

# Plot the time series pattern of the mean steps taken per 5 min interval
with(aggregatedData2, plot(interval, steps, type = "l", ylab = "Mean number of steps", xlab ="Intervalof the day"))

# Report which interval contains the maximum number of steps
maxStepsInterval <- which(aggregatedData2$steps == max(aggregatedData2$steps))
aggregatedData2[maxStepsInterval,]
```

## Imputing missing values

```{r}
# Compute the number of rows with missing values
# First indices of rows with missing values
missingStepsValues <- which(is.na(activityData$steps))
# Second Compute the number of rows with missing values
length(missingStepsValues)

# Create a new dataset with the NAs filled in
modifActivityData <- activityData
for(i in missingStepsValues) {
  modifActivityData[i,"steps"] <- aggregatedData2[aggregatedData2$interval == modifActivityData[i, "interval"], "steps"]
}

# Calculate the total number of steps taken per day (ignoring NAs)
aggregatedData3 <- aggregate(steps~date, data=modifActivityData, FUN="sum")

# Histogram of the total number of steps taken per day
with(aggregatedData3, hist(steps, main = "Number of steps per day (NAs filled in)", xlab = "Steps per day", col="red"))



```

## Are there differences in activity patterns between weekdays and weekends?
